services:
  helics:
    build: ../federates/broker
    container_name: broker
    environment:
      CST_HOST: "localhost"
      LOCAL_USER: "worker"
      POSTGRES_HOST: "localhost"
      MONGO_HOST: "mongodb://localhost"
      MONGO_PORT: "27017"
    volumes:
      - ../data:/data
      - ../config/tmp:/config/tmp:ro
      # - ../..:/workspaces:cached
    networks:
      cst_net:
        ipv4_address: 10.5.0.2
    command: /bin/bash -c "helics_broker --ipv4 -f 6 --loglevel=warning --name=broker --debugging"

  lv-grid_0:
    build: ../federates/grid
    container_name: lv-grid_0
    environment:
      CST_HOST: "broker"
      LOCAL_USER: "worker"
      POSTGRES_HOST: "localhost"
      MONGO_HOST: "mongodb://localhost"
      MONGO_PORT: "27017"
    volumes:
      - ../data:/data
      - ../config/tmp:/config/tmp:ro
      # - ../..:/workspaces:cached
    networks:
      cst_net:
        ipv4_address: 10.5.0.3
    depends_on:
      - helics
    command: /bin/bash -c "python main.py --name=grid --broker=broker --grid_file=kerber_landnetz_freileitung_1.xlsx"
    # command: sleep infinity

  loadhouse_0:
    build: ../federates/house_player
    container_name: loadhouse_0
    environment:
      CST_HOST: "broker"
      LOCAL_USER: "worker"
      POSTGRES_HOST: "localhost"
      MONGO_HOST: "mongodb://localhost"
      MONGO_PORT: "27017"
    volumes:
      - ../data:/data
      - ../config/tmp:/config/tmp:ro
      # - ../..:/workspaces:cached
    networks:
      cst_net:
        ipv4_address: 10.5.0.4
    command: /bin/bash -c "helics_player --input=/data/input/sample_house.csv --broker=broker --name=node_12 --local"
networks:
  cst_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
