federates:
  broker:
    name: broker
    build_folder: ${.name}
  grid:
    name: grid
    build_folder: ${.name}
    # grid_file: kerber_landnetz_freileitung_1.xlsx
    grid_file: grid_N2781730E4438792_80539_1_19.xlsx
    # grid_file: grid.xlsx
  house_player:
    name: house_player
    build_folder: ${.name}
    input_file: /data/input/sample_house.csv
    fill_remaining: true
  # house:
  #   name: house
  #   build_folder: ${.name}
  #   placement: [0, 2, 5, 8]
  # recorder:
  #   name: recorder
  #   build_folder: ${.name}
  #   output_file: /data/output/federation.log
  logger:
    name: logger
    build_folder: ${.name}
    output_file: /data/output/federation_processed.csv
  transformer:
    name: transformer
    build_folder: ${.name}
    voltage: 1.0
  # surrogate_collector:
  #   name: surrogate_collector
  #   build_folder: ${.name}
  #   output_file: /data/output/surrogate_data.h5

data_generation:
  latitude: 48.1351
  longitude: 11.5820
  matching_mode: "distance" # match by closest distance or population

general:
    start_time: 0
    end_time: 82800  # You can adjust this as needed
    time_step: 3600
    loglevel: warning