general:
 name: "grid"
 start_time: 
 end_time: 86400
 time_step: 300
 duration: 86400
federation:
 id: "mv-grid_0"
 name: "MediumVoltageGrid"
 class: "grid"
 config:
   layout: "kerber_landnetz_freileitung_1.xlsx"
   location: #"Forchheim" # [45.555, 28.444]
   simulator: "PandaPower" # "PyPSA"
 sub_federates:
   - id: "lv-grid_0"
     name: "LowVoltageGrid"
     class: "grid"
     config:
       placement: 3 # [3, 7]
       layout: "kerber_landnetz_freileitung_1.xlsx"
     sub_federates:
       - id: "loadhouse_0"
         name: "Load profile house"
         class: "load"
         config:
           placement: "fill"
           electrical_load: "H0" # "H25", "electricloadcurve.csv"
           heat_load: "" # "heatloadcurve.csv"
       - id: "house_0"
         name: "sim house"
         class: "house"
         config:
           placement: [4,6]
           model:
             class: "1R1C"
             resistance: "5 Ohm"
             capacitance: "8 F"
         sub_federates:
           - id: "battery_0"
             name: "BYD Battery"
             class: "battery"
             config:
               placement: 0
               capacity: "5kWh"
               power: "5 kW"
           - id: "pv_1"
             name: "Sunwell PV"
             class: "pv"
             config:
               capacity: "5 5 kW"
               max_production: "renewables_ninja2019_munich.csv"
           - id: "hems_0"
             name: "Smart HEMS"
             class: "hems"
             config:
               control_strategy: "mpc"
               accessible: ["battery_0", "pv_1"]
   - id: "pv_0"
     name: "PV Power Plant SWM"
     class: "pv"
     config:
       placement: 5
       capacity: "5 MW"
       control_range: [5,95]
       max_production: "renewables_ninja2019_munich.csv"