general:
  name: "TestGrid"
  start_time: 0
  end_time: 86400
  time_step: 3600
  duration: 86400
  use_meta_db: "mongo"
  use_data_db: "postgres"
federation:
  id: "local-grid"
  name: "Local Pandapower Grid"
  class: "grid"
  config:
    layout: "kerber_landnetz_freileitung_1.xlsx"
  sub_federates:
    - id: "loadhouse_0"
      name: "Load profile house"
      class: "load"
      config:
        placement: "fill"
        electrical_load: "sample_house.csv"