services:
    infdb-data:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
             - ./configs:/workspaces/infdb-data/configs:ro
             - ../meta_store:/workspaces/infdb-data/meta_store
             - ../config:/config:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env
        environment:
            - UV_LINK_MODE=copy
