services:
    infdb-data:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
             - ./configs:/workspaces/infdb-data/configs:ro  # for production
#            - .:/workspaces/infdb-data # for development only
#            - ../../src/infdb_package:/workspaces/infdb_package
#            - /workspaces/infdb-data/.venv # Exclude .venv from volume mount
#            - .vscode:/workspaces/.vscode:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env
        environment:
            - UV_LINK_MODE=copy
