name: CI

on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[cpu]

      # - name: Run Pytest
      #   run: |
      #     pytest --ignore=tests/integration
